language: haskell
install:
 - bundle install
 - travis_retry cabal install pandoc pandoc-citeproc
script: bundle exec rake site:deploy
env:
  global:
    secure: "DTpqY+yuvROkUofxsMJaRjfuniYAm3nujq0WlxrBEDxnE+rN8wx45XCs+xzaBhxn+KgNG4RVuJTvx6DhwJu3ocZNUdBgCVzJ6goXqfEEt8ogIp81flNGkU2+bEDHqL0Pfyd3L3NsGM5ZUPZ0d/1ovkOvDugMsGtNpvRjB25CXss="