language: haskell
install:
 - bundle install
 - travis_retry cabal install pandoc pandoc-citeproc
script: bundle exec rake site:deploy
env:
  global:
    secure: "iv8FPqAvV7K+oTkdCFdENjquelDb8I2aN6IQ44ZnmNeHINtWuundJjLmMMfIP9i4lOh5KZYIv0itbz2MOx0BcQaIq3pDGSkKM1Pa2OkHfO2i34YGA8YfOaEVnIg0e1w88767G4ROeea0QK71kTVy11yCR0Nhruj5oKE+5m/cdw8="