safe: false
lsi: false
pygments: true

relative_source: ../mfenner.github.io/
destination: ../mfenner.github.io-pages/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: mfenner

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml

permalink: /:categories/:year/:month/:day/:title

paginate: 10
paginate_path: "page:num"

title: Gobbledygook
name: Gobbledygook
description: Martin Fenner writes about how the internet is changing scholarly communication.
tagline:
url: http://blog.martinfenner.org
author:
  name: Martin Fenner
  orcid: 0000-0003-1419-2405
  email: mfenner@plos.org
  gravatar: abfd3f212a9252ecb14687a2c62f934b
  affiliation:
  github: mfenner
  twitter: mfenner

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://blog.martinfenner.org
source_url:      http://github.com/mfenner/blog
archive_path:    /archive.html
categories_path: /categories.html
tags_path:       /tags.html
rss_path:        /rss.xml
atom_path:       /atom.xml

excerpt_separator: <!--more-->

# Markdown Parser (standard Jekyll argument, extended to special parser)
markdown: pandoc
pandoc:
  skip: true
  flags: '--smart --mathjax --filter pandoc-citeproc --bibliography=bibliography/references.bib --csl=_styles/apa.csl'
  outputs:
    epub:
    pdf:

comments :
  provider : disqus
  disqus :
    short_name : gobbledy

analytics :
    provider : google
    google :
        tracking_id : 'UA-36379104-1'

scholar:
  style: ./_styles/plos.csl
  source: ./bibliography
  bibliography: 0000-0003-1419-2405.bib
  bibtex_filters:
    - latex
    - markdown
