permalink: /:categories/:year/:month/:day/:title

paginate: 10
paginate_path: "page:num"

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
pygments: true

destination: ../mfenner.github.io/

title: Gobbledygook
name: Gobbledygook
description: Martin Fenner writes about how the internet is changing scholarly communication.
tagline:
url: http://blog.martinfenner.org
author:
  name: Martin Fenner
  orcid: 0000-0003-1419-2405
  email: mfenner@plos.org
  affiliation:
  github: mfenner
  twitter: mfenner

# The production_url is only used when full-domain names are needed
# such as sitemap.txt
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.

production_url:  http://blog.martinfenner.org
source_url:      http://github.com/mfenner/blog
archive_path:    /archive.html
categories_path: /categories.html
tags_path:       /tags.html
rss_path:        /rss.xml
atom_path:       /atom.xml

## Markdown Parser (standard Jekyll argument, extended to special parser)
markdown: pandoc
pandoc:
  skip: true
  flags: '--smart --mathjax --bibliography=bibliography/references.bib --bibliography=bibliography/me.bib --csl=_styles/plos.csl'
  outputs:
    epub:
    pdf:

comments :
  provider : disqus
  disqus :
    short_name : gobbledy

analytics :
    provider : google
    google :
        tracking_id : 'UA-36379104-1'

scholar:
  style: ./_styles/plos.csl
  source: ./bibliography
